### PR TITLE
git update

### PR DESCRIPTION
**Pull request by gbayasgalan**
git update using <git pull> and <git fetch & git merge>

### CODE REVIEW

**Review by stefa2k — COMMENTED** [review]
What's the reason for the changes in `init-setup.yaml`?

**Comment by gbayasgalan** [comment]
> What's the reason for the changes in `init-setup.yaml`?

new roles added in `init-setup.yaml` and here: https://github.com/stereum-dev/ethereum2-ansible/pull/3/commits/70c8cdbcc93cb620babfd1d82c7dad655c43d390#diff-6f78551be385b5661ddd5a5793a1f17e61be9ec2aac687b5ddcddb5d994bf53aL1 'test' is added for testing purpose, but it's now removed.

**Comment by stefa2k** [comment]
We'll use `init-setup.yaml` as the playbook to setup a node from scratch. From my point of view there is no need to fetch for any updates because the node was just created and there can't be any new updates.

**Comment by gbayasgalan** [comment]
> We'll use `init-setup.yaml` as the playbook to setup a node from scratch. From my point of view there is no need to fetch for any updates because the node was just created and there can't be any new updates.

okey, got it, then I going to remove the update roles from `init-setup.yaml`

**Review by stefa2k — APPROVED** [review]
lgtm

**Pull request merged**
